images: inside/publish-to-sonatype

pipelines:
  default:
    - step:
        script:
          - openssl aes-256-cbc -pass pass:$opensslPassword -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - gradle publishFullPToSR -Psigning.keyId=A5E6CDB4 -Psigning.password=$signPassword -PossrhUsername=$ossrhUsername -PossrhPassword=$ossrhPassword
